version: '3.8'

services:

  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    networks:
      dummy_network:
        ipv4_address: 172.21.0.4

networks:
  dummy_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
