version: '3.8'

services:

  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    networks:
      mvpvm:
        ipv4_address: 172.21.0.4

  networks:
    default:
      name: mvpvm
      external: true
